# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(max_length=250),
        ),
    ]
